### ISSUE TITLE
Refactor dependencies

### ISSUE THREAD

**Issue by apiad** [autogoal/autogoal#10]
Correctly separate dependencies into:
- `core` (i.e., without any ML framework)
- `development` (e.g., pytest, coverage, mkdocs, etc.)
- `extras` (one group for each contrib module)

**Comment by AnshuTrivedi** [comment]
@apiad i would like to work on this issue .
Can you help me into how to preceed furteher in categorising dependencies?

**Comment by apiad** [comment]
Hey! Awesome, thanks! 

What we want is to take the `pyproject.toml` file and separate all dependencies into categories. 

The main dependencies would be the ones that are now in the `tool.poetry.dependencies` section, I think those need no change.

In the section `tool.poetry.dev-dependencies` leave *only* the dependencies that are need for development/testing: i.e., pytest, coverage, everything related with mkdocs.

And then create extra dependencies as explained here (https://python-poetry.org/docs/pyproject/#extras), creating one category for each of the `contrib` modules (https://github.com/autogoal/autogoal/tree/main/autogoal/contrib). So, one category for all dependencies in `autogoal/contrib/sklearn`, one for all that is needed for `autogoal/contrib/keras` and so on. Each category will be named as the `contrib` module to which it corresponds. 

So, for example, if I install `pip install autogoal[sklearn]` then only the main dependencies and those that are needed to import `from autogoal.contrib import sklearn` would be installed.

Makes sense?

**Comment by AnshuTrivedi** [comment]
@apiad  thanks for detailing issue.
What i understood is 
1. **core dependencies**
leave untouched  tool.poetry.dependecies and keep it in `core`
2. **developement dependencies**
remove unneccesary (contrib module) dependencies  from tool.poetry.dev_dependencies,
3. **extras dependencies**
`create tool.poetry.extras` like this
mysql = ["mysqlclient"]
pgsql = ["psycopg2"],
create categories for all in [contrib](https://github.com/autogoal/autogoal/tree/main/autogoal/contrib) as
tool.poetry.extras.keras
`keras = "^2.3.1"`
`tool.poetry.extras.gensim`  and same for other contrib modules in `pyproject.toml` file.
I need help in contrib module dependencies,please help me. I think misunderstood contrib dependencies grouping.

**Comment by apiad** [comment]
Exactly like that :+1:

**Comment by apiad** [comment]
For each folder in `contrib` there is one or more `.py` files. You would need to open those files and see what's imported, and from there see which dependencies that corresponds to...

**Comment by apiad** [comment]
Don't try to do all at once, if you can do for example just **one** extra with all of contrib that's OK to begin.

Then we take all of keras into it's own extra. Now we have 2 extras: keras and contrib. And so on, one at a time.

**Comment by apiad** [comment]
We did it!
