### ISSUE TITLE
Add configuration for `pip install autogoal[all]`

### ISSUE THREAD

**Issue by joogvzz** [autogoal/autogoal#11]
The installation command 'pip install autogoal[all]' misses **sklearn** and **tqdm** packages

**Comment by apiad** [comment]
Related with #10 . Solving that would solve this as well.

**Comment by apiad** [comment]
Except that we would need to add `all` to the optional dependencies. So I'm leaving this open for when the comment comes :sweat_smile:

**Comment by apiad** [comment]
Closed, finally solved by #17
