### ISSUE TITLE
Enrich documentation

### ISSUE THREAD

**Issue by geblanco** [autogoal/autogoal#23]
Hello AutoGoal Team!

Congrats for the project! It looks amazing!

I was tinkering around with the library and have several considerations:
- The documentation is still a bit harsh, are you planning on growing the current documentation? I.e.: The only way (I am aware of) to get the difference between a ConsoleLogger and a MemoryLogger is to look at the source code, no description is provided in the API section.
- Right now, examples are mixed up with the web page, while this is nice for reading, it is not so for testing, I found the plain python files inside the examples folder, but maybe linking those directly in the examples web page could be great, just like Google has (nice little button with a \<full source code link\>). What do you think?

I could happily  contribute on those things :)

Best,

**Comment by apiad** [comment]
Hey, thanks for the feedback! Yeah, you're definitely right, the documentation needs a LOT of polishing. Any suggestion you have here is much appreciated, and if you want to go ahead and make some improvements, even better :+1:! 

About the examples, yes, you're spot on. The examples are actually Python scripts which are automatically converted to Markdown with `docs/make_docs.py`. If you want to tinker with it, it should be possible to modify it to output the link to the script in the Markdown.

https://github.com/autogoal/autogoal/blob/main/docs/make_docs.py

Regarding the loggers and other stuff, it's all about putting docstrings in the right classes. The `make_docs.py` script also takes care of pulling those. So, yeah, feel free to tackle this, we'll be gladly waiting for your PR!

**Comment by geblanco** [comment]
Hello @apiad,

Okay, it sounds good to me! I'll have a look when my schedule gets loose. :)

**Comment by geblanco** [comment]
Hello @apiad,

I have tried to compile the docs with `make_docs.py`, when run from the docs folder, it crashes failing to find `mkdocs-base.yml`. Here is the error:

```bash
Traceback (most recent call last):
  File "make_docs.py", line 328, in <module>
    build_api()
  File "make_docs.py", line 128, in build_api
    with open(os.path.abspath(base_path / "mkdocs-base.yml"), "r") as fr:
FileNotFoundError: [Errno 2] No such file or directory: '/home/coder/autogoal/docs/mkdocs-base.yml'
```
I have fixed it, it is in the next PR
