### ISSUE TITLE
Dev environment tests fail

### ISSUE THREAD

**Issue by geblanco** [autogoal/autogoal#25]
Hi,

To get started with #23, I created the dev environment following the guides in the README, unfortunately, the tests fail.
Steps to reproduce:
1. Fork the project
2. Clone the forked project
3. `make pull`
4. `make shell`
5. `make test` (inside the docker container)

Error:

```bash
========================================================================================================== short test summary info ==========================================================================================================
FAILED tests/contrib/test_contrib.py::test_create_grammar_for_generated_class[CountVectorizerNoTokenize] - ValueError: Cannot find compatible implementations for interface <class 'types.Algorithm[List(Word()), List(Word())]'>
======================================================================================== 1 failed, 166 passed, 134 deselected, 7 warnings in 30.00s =========================================================================================
makefile:98: recipe for target 'test' failed
make: *** [test] Error 1
```

Any idea how that got wrong?

Best,

**Comment by apiad** [comment]
Yeah, this is one unit test that is failing because we are missing some configuration. It has been bugging me for a while. Run `make test-core` which are the tests related only to the core code and not the contribs.

I'm gonna leave this issue open to remember to fix this test.

Thanks :+1: !

**Comment by geblanco** [comment]
@apiad sure, I'll try with `test-core` suite!

**Comment by apiad** [comment]
Closed by the latest commit.
