### ISSUE TITLE
Cars dataset not existing

### ISSUE THREAD

**Issue by yacth** [autogoal/autogoal#37]
The uci_cars dataset isn't present in its folder
Using :
`from autogoal.datasets import cars`

Gives us :
`[Errno 2] No such file or directory: '/home/coder/autogoal/autogoal/datasets/data/uci_cars.zip'`

**Comment by apiad** [comment]
Related to issue #39

**Comment by apiad** [comment]
@all-contributors please add @yacth for discovering bugs

**Comment by apiad** [comment]
@EEstevanell can we try to replicate this?

**Comment by EEstevanell** [comment]
Yeah! I will look into this today

**Comment by apiad** [comment]
Closing this as we can no longer replicate it.
