### ISSUE TITLE
Change the dataset storage to a folder outside the project

### ISSUE THREAD

**Issue by apiad** [autogoal/autogoal#39]
**The problem:**
Right now the call to `autogoal.download(dataset)` stores each dataset inside a `data` folder in the project source. 
This is problematic for many reasons: First, data shouldn't be in the project source folder (even if .gitignored). Second, when autogoal is installed with `pip` it lands in `site-packages` and that location is often write-protected against non-root users.

**Proposed solution:**
Similar to what `nltk` or `gensim` do, simply create a `.autogoal` folder in `$HOME` and store everything there.

**Comment by EEstevanell** [comment]
dibs :)
