### ISSUE TITLE
Refactor logging and callbacks

### ISSUE THREAD

**Issue by apiad** [autogoal/autogoal#44]
**The problem**

Right now we have a `Logger` class that receives callbacks from `SearchAlgorithm`. Implementations of this include logging to terminal and files, as well as saving the intermediate steps. The `Logger` name is misleading. This is actually a `Callback` since logging is just one of the things that could be done. 

Likewise, there are many things that can be implemented as callbacks and are now hard-coded, e.g., the early stopping criteria, model serialization, etc. 

Finally, we already have a pretty nice logging system implemented with `rich`, but many places inside the library are not aware of this mechanism. There are lots of prints and custom progress bars around there.

**Proposed solution:**

- Refactor the `Logger` class to be called `Callback` and move it to its own namespace.
- Refactor all the custom print and progress bars to use the new logging system in `autogoal.logging` and `rich` progress bars.
- Implement as callbacks all the hard-coded behaviour inside `SearchAlgorithm` than can be extracted, such as early stopping, saving the best model and saving the search algorithm progress.

**Comment by alexfertel** [comment]
@apiad  I can take a look at this over the weekend!

**Comment by apiad** [comment]
All your :smile: !!
