### ISSUE TITLE
Refactor examples to use the RichLogger

### ISSUE THREAD

**Issue by apiad** [autogoal/autogoal#45]

**Comment by AnshuTrivedi** [comment]
@apiad May you help me explaining little more for better understanding what have to do?
I would love to contribute !

**Comment by apiad** [comment]
Sure! The examples in the `docs/examples` folder have this line somewhere:

https://github.com/autogoal/autogoal/blob/c6d7e13f79b18946d61b0111f8e35bfd32da4d8a/docs/examples/solving_uci_datasets.py#L175

Instead of instantiating a `ConsoleLogger` and a `ProgressLogger` we can replace those two by a single `RichLogger` which is in `autogoal.search`. This is a new logger that shows pretty printed stuff with syntax highlight, colors, etc., and is used in the CLI. 

What we want is to go over all examples, and wherever there is a `MemoryLogger` and a `ConsoleLogger` replace those by a single `RichLogger`.

And of course run them and make sure there are no obvious errors. Sadly we don't have unit tests for examples yet...

**Comment by apiad** [comment]
@AnshuTrivedi if you want to do it, let me know so we can mark it as `wip` and assign it to you :wink:

**Comment by AnshuTrivedi** [comment]
> @AnshuTrivedi if you want to do it, let me know so we can mark it as `wip` and assign it to you 😉

Sure ! 
Thanks.

**Comment by AnshuTrivedi** [comment]
> Sure! The examples in the `docs/examples` folder have this line somewhere:
> 
> https://github.com/autogoal/autogoal/blob/c6d7e13f79b18946d61b0111f8e35bfd32da4d8a/docs/examples/solving_uci_datasets.py#L175
> 
> Instead of instantiating a `ConsoleLogger` and a `ProgressLogger` we can replace those two by a single `RichLogger` which is in `autogoal.search`. This is a new logger that shows pretty printed stuff with syntax highlight, colors, etc., and is used in the CLI.
> 
> What we want is to go over all examples, and wherever there is a `MemoryLogger` and a `ConsoleLogger` replace those by a single `RichLogger`.
> 
> And of course run them and make sure there are no obvious errors. Sadly we don't have unit tests for examples yet...

@apiad do have to replace `ConsoleLogger` and a `ProgressLogger`  or  `MemoryLogger` and a `ConsoleLogger`  ?
or all three ?

**Comment by AnshuTrivedi** [comment]
I think it would be better to create task list for all unit tests for examples in one issue (just suggestion)
Any one willing  to contribute may write even single unit test.

**Comment by apiad** [comment]
> @apiad do have to replace `ConsoleLogger` and a `ProgressLogger` or `MemoryLogger` and a `ConsoleLogger` ?
> or all three ?

Just `ConsoleLogger` and `ProgressLogger`.

**Comment by apiad** [comment]
> I think it would be better to create task list for all unit tests for examples in one issue (just suggestion)
> Any one willing to contribute may write even single unit test.

We have #26 issue for tracking this... If you have any idea how can it be better organized, just go to that issue and let us know. We are open to any suggestion :smile:

**Comment by apiad** [comment]
Hey @AnshuTrivedi, I was just wondering if you're still interested in this issue? It's OK if you're busy with something else, or if you need any help, just let us know! 

Thanks :)

**Comment by apiad** [comment]
@EEstevanell would you mind taking over this issue?

**Comment by EEstevanell** [comment]
@apiad sure! I will look into this right away
