### ISSUE TITLE
Support for GANs module

### ISSUE THREAD

**Issue by AdityaNikhil** [autogoal/autogoal#49]
Hey there,
it's been a while since I talked about this idea on integrating GANs with AutoGoal.
So it's very simple idea for integrating gans module with autogoal. Which shall look like this,

```
from autogoal.ml import GANS

#initialize model
gan = GANS.dcgan()

#load train data
Data = gan.load_data(use_mnist=True)

#get samples from daa object
Samples = gan.get_samples(Data, n_samples=5)

#train the model
Gan.fit(train_ds=Data)

#get generated saples from model
Generated_samples = gan.generate_samples(n_samples=5)
```

Firstly am thinking to start off with simple GANs architecture and then we'll slowly add more gan architectures like Pix2Pix, WGAN, CycleGAN.....

**Support I need**,
I have the raw code ready to run GANs. I need your help in turning this raw code to a class and then a beautiful module which can  be easily accessed from AutoGoal like shown above.

@apiad ,I hope you like it. Also am hoping to get support from you in building this module.

Looking forward for your reply!

**Comment by apiad** [comment]
Hey! Thanks a lot for collaborating! I would love to have GANs in AutoGOAL. The only thing I would ask is that we spend a bit of time designing an API that looks like AutoGOAL. I think your API proposal is pretty close and I like to work with you polishing it a little bit more. If this is ok with you I'll be back in a couple days with some suggestions! 😄

**Comment by AdityaNikhil** [comment]
Hey @apiad ,
Am glad you liked it. Definitely we'll spend time on designing. Can't wait to work with you. 
Hope to see you soon!!!! 😄😄😄

**Comment by AdityaNikhil** [comment]
Hey @apiad,
It's been a while since I heard from you. I just wanted ask if from when can we start working, because, I really like to be a part of this project and have many ideas to develop it. Looking forward to contribute my best.

**Comment by apiad** [comment]
Hey @AdityaNikhil, sorry for the radio silence, been dealing with some things.

Let's do the following because I think it's best to discuss on top of code than on abstract designs: Do your fork and add `autogoal/experimental/gan.py` (please create the experimental folder if it doesn't exist).

Try to add there one class that represents what you think is the most common GAN API, and we'll work on the design through PRs. My only recommendation is to try to detach the data from the training process, so instead of `load_data`, assume there is some dataset with the format you need, so you only need to pass that `data` object to the `fit` method.

I propose something resembling this, which is very similar to your proposal:

```
from autogoal.experimental.gans import DCGAN
from autogoal.datasets import mnist # <--- this is an example, dunno if it works yet

gan = DCGAN()
data = mnist.load()

gan.fit(data)
samples = gan.generate(n_samples=5)
```

If you like it feel free to start working on it and PR as soon as you want some feedback. We'll move the actual discussion of the design to that PR, let's keep here just the top-level discussion.

Thanks :pray:

**Comment by AdityaNikhil** [comment]
Hey @apiad , 
Awesome to hear back from you. I just have one concern that I currently have exams going on till end of this month. So I cannot work full fledged on this till end of this month but will be working full time on this from Dec 1st.

**Comment by apiad** [comment]
Of course, don't worry! Feel free to work at your own pace, this is open-source, we're all doing this for free :). 
Let me know whenever you want to discuss something or have any questions. And good luck with your exams!

**Comment by AdityaNikhil** [comment]
Hey @apiad,
Been a long time, hope you're fine. This is just a heads up to let you know, I've started working on it and PR it as soon as possible. Please reply to this just so I could know, you're out there!

**Comment by apiad** [comment]
Great!!! I'll be waiting, let me know if you need any help or want to discuss anything :smile:

**Comment by AdityaNikhil** [comment]
Hey @apiad ,
I'm trying to get familiar with AutoGoal, I've successfully pulled AutoGoal using docker. When I try to run the cars demo, I face this error. I'm using windows 10. Can you please look into this issue.

![image](https://user-images.githubusercontent.com/30192967/102078537-16192b80-3e31-11eb-9e01-dfffb77dc37e.png)

**Comment by AdityaNikhil** [comment]
Hey @apiad, I seriously need your help in setting up the AutoGoal environment on my windows 10 pc. I'm trying to get comfortable with AutoGoal first. I was checking the [**contributing** ](https://autogoal.github.io/contributing/)section. I'm afraid all the commands are written in Linux. I'm unable to setup the environment.

**Comment by BFergerson** [comment]
@AdityaNikhil, ran into the same issue. You have to run `autogoal data download uci_cards` on the autogoal container first.

**Comment by AdityaNikhil** [comment]
Hey @BFergerson ,
I get the following error when I type the above command,
```
coder@04320895b278:~/autogoal$ autogoal data download uci_cards
⚠️  The command failed with message:
"'uci_cards'".
```

**Comment by BFergerson** [comment]
Apologies, wrote from memory. I believe it's `uci_cars`. If you just do `autogoal data download` it'll show what's possible. You could also do `autogoal data download all` to download all datasets.

**Comment by apiad** [comment]
Thanks @BFergerson, that's a perfect answer. This is a good issue to track, the demo should more correctly inform when a dataset is not available, maybe even suggest to download it...

**Comment by apiad** [comment]
@all_contributors please add @BFergerson and @AdityaNikhil for bugs.

**Comment by apiad** [comment]
@allcontributors please add @BFergerson and @AdityaNikhil for bugs.

**Comment by apiad** [comment]
@allcontributors please add also @AdityaNikhil for bug.

**Comment by apiad** [comment]
@allcontributors add @AdityaNikhil for bug.

**Comment by apiad** [comment]
Thank you both! Sorry for being off-grid for a while, December was a rough month, but I'm back now. Let me know if you need any help at all.

**Comment by AdityaNikhil** [comment]
Hey @apiad, glad to see you. It's been a while..!
Hoping to run things faster now..!

**Comment by apiad** [comment]
Hey @AdityaNikhil, long time no see! Let me know if you're still interested in this issue. No rush, I just want to know if I should leave the issue open. I would love to see those GANs working! :smile: 

Anything you want to discuss over here...

**Comment by AdityaNikhil** [comment]
Hey @apiad,
I still want to integrate the GANs but I am currently caught up with other works. So I don't think I'll be able to work on this for some weeks.
