### ISSUE TITLE
Automatic release to PyPi and Docker Hub

### ISSUE THREAD

**Issue by apiad** [autogoal/autogoal#53]
The purpose is to automatically build a Python package with Poetry and submit to PyPi on every release. Also, create a custom image in DockerHub.

**Comment by leynier** [comment]
@apiad I could take care of the automatic publication in PyPi through a GitHub Action and Poetry, only you would have to tell me under which circumstance you want it to be published.

**Comment by apiad** [comment]
This was solved by #65
