### ISSUE TITLE
load_cfg

### ISSUE THREAD

**Issue by joogvzz** [autogoal/autogoal#62]
As exists a function _generate_cfg_ it is necessary a function _load_cfg_.

**Comment by apiad** [comment]
What would the purpose of this new function?

**Comment by joogvzz** [comment]
R/ Once we have saved a grammar, at any time, you can load it to dynamically build the classes that the grammar represents. Also, some researchers might write AutoGOAL grammars as a simpler form of coding instead of Python classes.
