### ISSUE TITLE
SeqAlgorithm problems

### ISSUE THREAD

**Issue by lucas-FP** [autogoal/autogoal#73]
I am currently working on my graduation course's final project and introducing new methods to deal with portuguese text representation in Autogoal. I already had some working code, but everything stopped working when I updated the autogoal framework a couple of weeks ago. 

I correctly renamed all the `Lists` to `Seq` algorithms, changed all other types that got new names and started using the `Supervised` type in the input. Unfortunately, I still couldn't find valid pipelines with the small registry that I was using (it was the same code and same registry that was working some weeks before).

So I started debugging and noticed that only the first algorithm of the graph was being wrapped by the `SeqAlgorithm`. In [line 494 of algorithm.py](https://github.com/autogoal/autogoal/blob/e9afac4f26061d03f1f6827e34c79c663b899cb3/autogoal/kb/_algorithm.py#L494) the traversed algorithms are the ones in `registry` and not the ones in the `pool` with wrapped `SeqAlgorithms`. Changing that line to iterate over `pool` kind of solved the issue.

Now the pipelines were found, but whenever the sampler tried to initialize an algorithm that was wrapped by the `SeqAlgorithm` and had parameters in the `_init_` method, an error was thrown because those parameters were not passed.

This was a trickier one to solve. I noticed that in [line 315 of cfg.py](https://github.com/autogoal/autogoal/blob/e9afac4f26061d03f1f6827e34c79c663b899cb3/autogoal/grammar/_cfg.py#L315) the signature being retrieved for `SeqAlgorithm`s did not contain the inner class `__init__` parameters. I solved this one by creating a new method `get_inner_signature` in `SeqAlgorithm`s that returns the inner class's `__init__` signature. So back at  [line 315 of _cfg.py](https://github.com/autogoal/autogoal/blob/e9afac4f26061d03f1f6827e34c79c663b899cb3/autogoal/grammar/_cfg.py#L315) I could check if the class had that method implemented and, if so, used it instead of the `__init__` signature.
The problem now is that the pipelines I get after these changes are using a lot of unnecessary `SeqAlgorithm`s that doesn't make sense.

So, now I am in a spot where I do not know if I was doing something wrong in the first place and all these changes I made were actually not corrections, or if these changes I made were really necessary and I still need to dig deeper. If someone could point me out to the right direction I will be very grateful.

**Comment by apiad** [comment]
Hey @lucas-FP! It seems we screwed big time :sweat: with that refactor! We have found out that the new graph algorithm indeed adds a lot of unnecessary nodes, especially nodes whose output are not used. We are in plans of solving that, basically when adding a new node to the graph, marking which outputs of previous nodes it uses, so that only pipelines with no unnecessary outputs are sampled.

It would be great to have time to sit and chat with you more deeply about the problems you're running into because I'm sure that will give us a lot of info about what's being broken. And of course, if you have any change you want to PR that would be awesome as well!

**Comment by lucas-FP** [comment]
Hi @apiad, I just noticed that making the `Word` type not a subclass of `Sentence` solved the issue (at least until there is a better solution).
I'll open a PR with the other fixes I made in order to allow the `SeqAlgorithm` to work properly.

About the chat, I also think it would be great :grin:. Should we schedule a meeting via email?

**Comment by apiad** [comment]
@all-contributors add @lucas-FP for bugs and code
