### ISSUE TITLE
Error when saving models

### ISSUE THREAD

**Issue by joogvzz** [autogoal/autogoal#76]
This error appears when saving the pipeline's models
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-24-21bff7ebb822> in <module>()
      1 with open('model_reviews.pkl', 'wb') as f:
----> 2     model.save(f)
      3 
      4 print('Done!')

/usr/local/lib/python3.7/dist-packages/autogoal/ml/_automl.py in save(self, fp)
    102         """
    103         self._check_fitted()
--> 104         pickle.Pickler(fp).dump(self)
    105 
    106     @classmethod

PicklingError: Can't pickle <class 'abc.SeqAlgorithm[TabTokenizer]'>: attribute lookup SeqAlgorithm[TabTokenizer] on abc failed

**Comment by apiad** [comment]
This is a generalized error, when we redesigned the semantic types, all saving and loading broke. We have to redesign the whole save/load functionality from scratch.
