### ISSUE TITLE
(version 0.6.0)Error when saving models(other)

### ISSUE THREAD

**Issue by joogvzz** [autogoal/autogoal#77]
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-12-21bff7ebb822> in <module>()
      1 with open('model_reviews.pkl', 'wb') as f:
----> 2     model.save(f)
      3 
      4 print('Done!')

/usr/local/lib/python3.7/dist-packages/autogoal/ml/_automl.py in save(self, fp)
    102         """
    103         self._check_fitted()
--> 104         pickle.Pickler(fp).dump(self)
    105 
    106     @classmethod

PicklingError: Can't pickle <class 'abc.SeqAlgorithm[WhitespaceTokenizer]'>: attribute lookup SeqAlgorithm[WhitespaceTokenizer] on abc failed

**Comment by apiad** [comment]
Closing as it is the same issue as #76
