### ISSUE TITLE
Add support for Convolutional Neural Networks

### ISSUE THREAD

**Issue by stdevAdrianPaez** [autogoal/autogoal#81]
The objective of this issue is to insert Convolutional Neural Networks (CNN). The main idea is to solve problems like image segmentation. For now, we are guiding by class `KerasImageClassifier`, we think the final approach for CNN is close to that.

**Comment by apiad** [comment]
Sugiero que se concentren en un algoritmo, por ejemplo, segmentación. Con eso es suficiente.
