### ISSUE TITLE
Identify text language

### ISSUE THREAD

**Issue by yasmany93** [autogoal/autogoal#87]
Using the libraries numpy, Scipy, nltk and  Scikit-learn, and Bayesian Network to identify a text language (Spanish and English but with the possibility of adding more).

**Comment by apiad** [comment]
Aprobado. Recuerda que es necesario incluir algo adicional al problema cómo tratamiento de jerga, o más de una variante regional del mismo idioma, o más de un idioma por documento (segmentar), o algo similar.
