### ISSUE TITLE
Named Entity Detection

### ISSUE THREAD

**Issue by aldorivero** [autogoal/autogoal#91]
Add spacy algorithms to find entities in unstructured text. Based on the nlp spacy's algorithms and using en_core_web_sm model to process texts searching for entities.

**Comment by apiad** [comment]
Debe ser entrenable para cualquier modelo de entidades, *no* simplemente ejecutar Spacy y detectar las entidades básicas que vienen pre-entrenadas.

**Comment by aldorivero** [comment]
Claro profe...la idea es hacer un contrib basado en el funcionamiento d spacy...no ejecutar spacy y ya

**Comment by aldorivero** [comment]
Profe m sugireron q suba el commit en la carpeta experimental

**Comment by apiad** [comment]
Sip, así es :+1: dentro de una carpeta propia en `autogoal/experimenta/...` para que cada contribución nueva esté aislada de las demás, y se pueda probar independientemente.
