### ISSUE TITLE
Add DrQA system from Facebook

### ISSUE THREAD

**Issue by dcordb** [autogoal/autogoal#95]
From the [project page](https://github.com/facebookresearch/DrQA) :

"DrQA is a system for reading comprehension applied to open-domain question answering. In particular, DrQA is targeted at the task of "machine reading at scale" (MRS)."

The idea is to integrate this system into Autogoal.

**Comment by dcordb** [comment]
Unfortunately, this project is kind of difficult to work with because it has a few scripts that train and do other stuff, but they didn't implement an API to use this, so I'd like to add [this](https://github.com/autogoal/autogoal/issues/103) instead.

**Comment by apiad** [comment]
Ok
